#ifndef FE_ERRORS_CODE_H
#define FE_ERRORS_CODE_H

typedef enum EN_FE {
    FE_ERROR_NONE = 0,
    FE_ERROR_INVALID_PARAM,
    FE_ERROR_FILE_IO,
    FE_ERROR_UNSUPPORTED_FORMAT,
    FE_ERROR_MEMORY_ALLOCATION,
    FE_ERROR_PROCESSING,
    FE_ERROR_INIT_AUDIO_INPUT_FAILED,
    FE_ERROR_INIT_AUDIO_OUTPUT_FAILED
} EN_FE;

#endif /* FE_ERRORS_CODE_H */   