/**
 * @file tables.h
 * @brief Extern declarations for precomputed ROM tables.
 *
 * Auto-generated by ref/generate_tables.py — DO NOT EDIT BY HAND.
 * Frame length N = 256
 */
#pragma once

#include "rtafe/fe_types.h"

/* ── Window function tables (Q1.15) ──────────────────── */
extern const q15_t window_hann_256[256];
extern const q15_t window_hamming_256[256];
extern const q15_t window_blackman_256[256];
extern const q15_t window_sine_256[256];

/* ── FFT twiddle factors (Q1.31), N/2 entries ─────── */
extern const q31_t twiddle_cos_256[128];
extern const q31_t twiddle_sin_256[128];

